#!/bin/bash
if [[ -z $1 ]] ; then
  if [[ -e winpeas.txt ]] ; then
    cat winpeas.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" > winpeas.nc.txt
    gedit winpeas.nc.txt
  else
    if [[ -e linpeas.txt ]] ; then
      cat linpeas.txt | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g" > linpeas.nc.txt
      gedit linpeas.nc.txt
    else
      echo "No Winpeas or Linpeas file found (linpeas.txt or winpeas.txt, no caps).."
      echo "Either specify a file (or files) or rename your winpeas or linpeas output"
    fi
  fi
else
  cat $1 $2 $3 $4 $5 $6 $7 $8 $9 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"
fi
